CHANGELOG.md, README.md, composer.json, src/Exception/BatchException.php
=> Remove useless interface, minor fix in readme

CHANGELOG.md, spec/HttpClientFlexibleSpec.php, src/HttpClientFlexible.php
A flexible http client implements both interface and can emulate one of the contract if not present in the injected http client.
=> Add flexible http client

CHANGELOG.md, composer.json, spec/HttpClientRouterSpec.php, src/HttpClientRouter.php
| Related tickets | fixes #12
| Documentation   | php-http/documentation#103
Explained in #12
=> Add http client router feature

CHANGELOG.md, spec/PluginClientSpec.php, src/PluginClient.php
| Related tickets | https://github.com/php-http/HttplugBundle/issues/26
| Documentation   | https://github.com/php-http/documentation/pull/109
This PR gives the possibility to add debug plugins. A debug plugin is executed between each normal plugin
With this PR we can show better diffs and how different plugins are changing the requests/responses.
=> Added possibility for debug plugins

CHANGELOG.md, spec/Plugin/AddHostPluginSpec.php, src/Plugin/AddHostPlugin.php
| BC breaks?      | only if you relied on the bug
The AddHostPlugin did not look at the port and thus the port was either the default or in the case of overriding an existing host the port specified in the request.
It makes more sense to overwrite the port along with the domain and protocol.
``` php
$uriFactory = new \Http\Message\UriFactory\GuzzleUriFactory();
new AddHostPlugin($uriFactory->createUri('http://localhost:8000'));
```
=> AddHostPlugin must also handle the port

src/Plugin/ErrorPlugin.php
Phpdoc adjust.
The doc said "by default" but there is no options to change behaviour.
=> adjust phpdoc of error plugin

CHANGELOG.md, spec/HttpClientPool/LeastUsedClientPoolSpec.php, spec/HttpClientPool/RandomClientPoolSpec.php, spec/HttpClientPool/RoundRobinClientPoolSpec.php, spec/HttpClientPoolItemSpec.php, src/Exception/HttpClientNotFoundException.php, src/HttpClientPool.php, src/HttpClientPool/LeastUsedClientPool.php, src/HttpClientPool/RandomClientPool.php, src/HttpClientPool/RoundRobinClientPool.php, src/HttpClientPoolItem.php
| Related tickets | fixes #8 
| Documentation   | https://github.com/php-http/documentation/pull/134
Add a Http Client Pool as discussed in #8
=> Add http client pool

src/Plugin/HeaderAppendPlugin.php, src/Plugin/HeaderDefaultsPlugin.php, src/Plugin/HeaderRemovePlugin.php, src/Plugin/HeaderSetPlugin.php
Make phpdoc more specific
The header plugins should be unambigous without having to study the implementation code.
=> clarify header plugin phpdoc

CHANGELOG.md, spec/Plugin/RedirectPluginSpec.php, src/Plugin/RedirectPlugin.php
| Related tickets | fixes #37, replaces #38 
| Documentation   | /
=> Fix redirect from http -> https

CHANGELOG.md, composer.json, spec/EmulatedHttpAsyncClientSpec.php, spec/HttpClientPoolItemSpec.php, spec/Plugin/AddHostPluginSpec.php, spec/Plugin/CookiePluginSpec.php, spec/Plugin/DecoderPluginSpec.php, spec/Plugin/ErrorPluginSpec.php, spec/Plugin/HistoryPluginSpec.php, spec/Plugin/RedirectPluginSpec.php, spec/Plugin/RetryPluginSpec.php, spec/PluginClientSpec.php, src/HttpAsyncClientEmulator.php, src/Plugin.php, src/PluginClient.php
| Related tickets | fixes #34 , replace #35
| Documentation   | /
See issue #34 and discussion in #35 also for more information
=> Use http based promise in emulated trait and specs

CHANGELOG.md, spec/Plugin/AddPathPluginSpec.php, spec/Plugin/BaseUriPluginSpec.php, src/Plugin/AddPathPlugin.php, src/Plugin/BaseUriPlugin.php
| BC breaks?      | no since this is a kind of bug regarding the situation
| Related tickets | N/A
| Documentation   | https://github.com/php-http/documentation/pull/163
This bugfix permits to keep the base path of an URI on the `AddHost` plugin.
With the following PHP code example:
```php
$httpClient = new HttpMethodsClient(
new PluginClient(HttpClientDiscovery::find(), [
new AddHostPlugin(UriFactoryDiscovery::find()->createUri('https://logs.domain.com/api')),
new ErrorPlugin(),
]),
MessageFactoryDiscovery::find()
);
$httpClient->get('/users');
```
The https://logs.domain.com/users URL will be called instead of /api/users.
The base path should be …
=> Add AddPathPlugin and BaseUriPlugin

CHANGELOG.md, spec/Plugin/DecoderPluginSpec.php, src/Plugin/DecoderPlugin.php
| BC breaks?      | no/yes
| Deprecations?   | no/yes
This PR updates the DecoderPlugin to use the right decoder to manage deflate content-encoding and disable compress as there is no support in PHP and nobody uses it
This is the solution proposed by @joelwurtz in https://github.com/php-http/message/issues/64#issuecomment-255958592 to the problem is described in https://github.com/php-http/message/issues/64
``` php
<?php
require 'vendor/autoload.php';
$decoderPlugin = new Http\Client\Common\Plugin\DecoderPlugin();
$pluginClient = new Http\Client\Common\PluginClient(
Http\Discovery\HttpClientDiscovery::find(),
[$decoderPlugin]
);
$response = $pluginClient->sendRequest(
new …
```
=> Fix deflate encoding handling and disable compress encoding

CHANGELOG.md, spec/Plugin/QueryDefaultsPluginSpec.php, src/Plugin/HeaderAppendPlugin.php, src/Plugin/QueryDefaultsPlugin.php
=> Added QueryDefaultsPlugin

CHANGELOG.md, src/PluginClient.php
| Deprecations?   | yes
| Related tickets | fixes #60 
| Documentation   | N/A
The `PluginClient` now triggers a deprecation notice when the `debug_plugins` option is set.
The `debug_plugins` option was used by the HttplugBundle collector, but since https://github.com/php-http/HttplugBundle/pull/128 is merged, it's no longer required.
=> deprecate debug_plugin options

.travis.yml
| Related tickets | N/A
| Documentation   | N/A
This is about fixing travis-ci HHVM build. See https://travis-ci.org/php-http/client-common/jobs/240025931.
=> Use trusty dist for travis-ci build

CHANGELOG.md, spec/PluginClientFactorySpec.php, src/PluginClientFactory.php
| Related tickets | partially https://github.com/php-http/HttplugBundle/issues/109
| Documentation   | TODO
This is required to display plugins created by 3rd party libraries in the HttplugBundle profiler. See https://github.com/php-http/HttplugBundle/issues/109#issuecomment-300461535 for all puzzle pieces.
=> add plugin client factory

spec/PluginClientFactorySpec.php, src/PluginClientFactory.php
| Related tickets | fixup #71 
| Documentation   | n/a
In #71, I missed to remove the `client_name` option from the options array before using it as `PluginClient` constructor third argument.
Before choosing to use `unset`, I was thinking to add the `client_name` option to `PluginClient`, use the `OptionsResolver` to set a default client name and add a getter to retrieve the client name. I don't choosed this way to not change anything in `PluginClient`, but if you find this solution better than the `unset` one, I would be happy to update this PR.
=> Do not pass client_name option to PluginClient constructor

CHANGELOG.md, spec/HttpClientPool/LeastUsedClientPoolSpec.php, spec/HttpClientPool/RandomClientPoolSpec.php, spec/HttpClientPool/RoundRobinClientPoolSpec.php, spec/HttpClientPoolItemSpec.php, src/Exception/HttpClientNotFoundException.php, src/HttpClientPool.php, src/HttpClientPool/LeastUsedClientPool.php, src/HttpClientPool/RandomClientPool.php, src/HttpClientPool/RoundRobinClientPool.php, src/HttpClientPoolItem.php
Reverts php-http/client-common#47
=> Revert "Removed the HTTPClientPool feature"

CHANGELOG.md, spec/Plugin/CookiePluginSpec.php, src/Plugin/CookiePlugin.php
| Related tickets | fixes #62
The changes make cookies set for main domain available for subdomains as well, as described in [RFC 6265](https://tools.ietf.org/html/rfc6265#section-5.2.3)
=> Cross subdomain cookie sharing issue

composer.json, spec/Plugin/ContentTypePluginSpec.php, src/Plugin/ContentTypePlugin.php
| Related tickets | mentioned in #82 
| Documentation   | https://github.com/php-http/documentation/pull/204
Add a new plugin which allow to detect JSON and XML content in body request and automatically set the right content-type header.
Set the content-type header is often unpleasing and detect whether the content is JSON or XML is relatively simple so it could save time.
``` php
$contentTypePlugin = new ContentTypePlugin();
$pluginClient = new PluginClient(
HttpClientDiscovery::find(),
[$contentTypePlugin]
);
```
- [x ] Documentation pull request created (if not simply a bugfix)
=> Add Content-type plugin to set content-type header automatically

CHANGELOG.md, composer.json, src/Plugin/CookiePlugin.php
| Related tickets | fixes #46
Supports more cookie date formats in the Cookie Plugin
=> Supports more cookie date formats in the Cookie Plugin

spec/Plugin/RetryPluginSpec.php, src/Plugin/RetryPlugin.php
| Related tickets | #79
| Documentation   |
As discussed in #79, the default delay function is not very delaying at all. With 10 retries, the delays (in seconds) of the old impl are:
```
0.001
0.002
0.004
0.008
0.016
0.032
0.064
0.128
0.256
0.512
1.024
```
I've simply multiplied by 100 here, so the new delays are:
```
0.1
0.2
0.4
0.8
1.6
3.2
6.4
12.8
25.6
51.2
102.4
```
Open to other suggests for a better delay.
=> RFC: update retry plugin backoff default to be more sensible

spec/Plugin/QueryDefaultsPluginSpec.php, src/Plugin/QueryDefaultsPlugin.php
=> Improved performance of QueryDefaultsPlugin

CHANGELOG.md, spec/Plugin/ErrorPluginSpec.php, src/Plugin/ErrorPlugin.php
| Related tickets | #77 
| Documentation   | https://github.com/php-http/documentation/pull/235/
cf #77
=> Add an option to only throw exception on 5XX error codes

CHANGELOG.md, spec/Plugin/DecoderPluginSpec.php, src/Plugin/DecoderPlugin.php
Decoder will now remove the header instead of setting it to an empty array
It fixes compatibility of this plugin with https://github.com/Nyholm/psr7 (and so certainly the PSR7 standard), as it throws an exception when setting a header with an empty array, cf this line : https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L80
=> Remove header if there is no more encoding value

CHANGELOG.md, spec/Plugin/RetryPluginSpec.php, src/Deferred.php, src/Plugin/RetryPlugin.php
It adds a deferred class which allow to resolve retry in an async way (no more wait call)
Previously using retry plugin would force async to be sync
=> Use deferred to be full async in retry

spec/Plugin/RetryPluginSpec.php, src/Plugin/RetryPlugin.php
| Related tickets | fixes #109
I revert the changes to RetryPlugin as a temporary fix for #109. Only consider this if we cannot properly fix it (as attempted in #110)
=> Do not use defer

CHANGELOG.md, spec/Plugin/CookiePluginSpec.php, src/Plugin/CookiePlugin.php
Concatenate multiple cookies
| Related tickets | fixes #54 
Makes the cookie plugin only add one cookie header with all cookies separated by ;
=> Fix Cookie handling as per RFC 6265 Section 5.4

.travis.yml, composer.json, phpspec.ci.yml, spec/HttpClientPool/LeastUsedClientPoolSpec.php, src/BatchClient.php, src/HttpAsyncClientEmulator.php, src/HttpClientDecorator.php, src/HttpClientEmulator.php, src/HttpClientPool.php, src/HttpClientPoolItem.php, src/HttpClientRouter.php, src/HttpMethodsClient.php, src/PluginClient.php
| BC breaks?      | not sure yet
| Documentation   | not sure it's needed yet
This PR (like https://github.com/php-http/discovery/pull/115) is to test and allow HTTPlug 2 (and PSR-18)
=> Allow HTTPlug 2.0

CHANGELOG.md, src/PluginClient.php
| Related tickets | partially #115
This PR drops the only deprecation present in 1.x branch.
=> [2.0] Remove deprecations

spec/PluginClientSpec.php, src/PluginClient.php
| Related tickets | partially #115, concludes #116 
As reported in https://github.com/php-http/client-common/pull/116#issuecomment-440182100, this removes the remainder parts of `debug_plugin`.
=> [2.0] Remove plugin chain debug

CHANGELOG.md, spec/Plugin/RetryPluginSpec.php, src/Plugin/RetryPlugin.php
| BC breaks?      | kindof
| Related tickets | fixes #80 
Do not retry if the error is caused by the server returning a HTTP error code indicating that the request was bad.
There is no point in retrying those.
=> adjust decider to not retry client errors

spec/Plugin/RedirectPluginSpec.php, src/Plugin/RedirectPlugin.php
| Related tickets | fixes #121
The plugin is not supposed to be extended. The tests have been hacking into the setup of the plugin itself and need to be adjusted.
- Changelog is updated in #123
=> Make RedirectPlugin final

CHANGELOG.md, spec/Plugin/AddPathPluginSpec.php, src/Plugin/AddPathPlugin.php
Instead of throwing `new \LogicException('URI path cannot end with a slash.');` when the URI path ends with a slash, this PR will rtrim it automatically.
Today was a day that we merged a PR that had successful CI builds but broke during deployment. The reason? The parameters set on the server ended with a `/`.
I don't really understand the reason for throwing exceptions this hard, while they can be recovered. Every time somebody converts a Guzzle client to HTTPlug I have to warn them that we first need to change the URI's everywhere to remove the ending slashes. And sometimes that breaks for no reason.
=> AddPathPlugin > Trim ending slash on path

CHANGELOG.md, spec/HttpClientPool/HttpClientPoolItemSpec.php, spec/HttpClientPool/LeastUsedClientPoolSpec.php, spec/HttpClientPool/RandomClientPoolSpec.php, spec/HttpClientPool/RoundRobinClientPoolSpec.php, spec/HttpClientRouterSpec.php, spec/HttpMethodsClientSpec.php, spec/Plugin/AddPathPluginSpec.php, src/BatchClient.php, src/BatchClientInterface.php, src/Deferred.php, src/EmulatedHttpAsyncClient.php, src/EmulatedHttpClient.php, src/HttpClientPool.php, src/HttpClientPool/HttpClientPool.php, src/HttpClientPool/HttpClientPoolItem.php, src/HttpClientPool/LeastUsedClientPool.php, src/HttpClientPool/RandomClientPool.php, src/HttpClientPool/RoundRobinClientPool.php, src/HttpClientRouter.php, src/HttpClientRouterInterface.php, src/HttpMethodsClient.php, src/HttpMethodsClientInterface.php
| Related tickets | partially #20 
| Documentation   | https://github.com/php-http/documentation/pull/244
Mark the remaining things final.
See #20
=> mark classes as final and methods and properties as private

composer.json
IMHO PHP-cs-fixer is not a dependency. It is a tool like PHPStrom. 
One should not require tools in composer.json.
=> Remove php-cs-fixer from dependencies

src/Plugin/ForwardCompatibilityPlugin.php, src/Plugin/VersionBridgePlugin.php, src/VersionBridgeClient.php
To avoid updating all our plugins and the HTTPlug bundle, we can be forward compatible. 
https://3v4l.org/pn47M
https://3v4l.org/2kgtG
=> Added a way to be forward compatible with version 2.0

src/BatchClient.php, src/EmulatedHttpAsyncClient.php, src/FlexibleHttpClient.php, src/HttpClientDecorator.php, src/HttpClientPool.php, src/HttpClientPool/HttpClientPool.php, src/HttpClientPool/HttpClientPoolItem.php, src/HttpClientRouter.php, src/HttpClientRouterInterface.php, src/HttpMethodsClient.php, src/Plugin/AddPathPlugin.php, src/PluginClient.php, src/PluginClientFactory.php
We should show that we support PSR-18. I've replaced `Http\Client\HttpClient` with `Psr\Http\Client\ClientInterface` on all the places where we consume a client. 
This will fix #122
=> Support PSR-18

src/Plugin/VersionBridgePlugin.php, src/VersionBridgeClient.php
=> Added backwards compatibility layer

CHANGELOG.md, spec/Plugin/RetryPluginSpec.php, src/Plugin/RetryPlugin.php
| Deprecations?   | yes
| Related tickets | preparation for #139
| Documentation   | Callbacks are generally not documented at http://docs.php-http.org/en/latest/plugins/retry.html ...
Rename callback method in retry plugin options.
Make room for response decider in version 2.
- not needed
=> rename decider to exception_decider to make room for response_decider in version 2

src/BatchClient.php, src/EmulatedHttpAsyncClient.php, src/FlexibleHttpClient.php, src/HttpClientDecorator.php, src/HttpMethodsClient.php, src/PluginClient.php, src/PluginClientFactory.php
Our 2.x branch is compatible with PSR-18. The master branch should also be compatible. 
Ive ipdated all places where we are **consuming** a httplug client. They do now support both httplug 1.x and PSR-18.
FYI @gmponos
=> Make sure we can use PSR-18 clients in version 1.x

CHANGELOG.md, spec/Plugin/AddPathPluginSpec.php, src/Plugin/AddPathPlugin.php, tests/Plugin/AddPathPluginTest.php
| Related tickets | fixes #118, fixes #113
What if we stored all the results of our rewrite and make sure we never rewrite a url that were stored as a result?
=> Dont add path to an url we already added a path to.

composer.json, src/Plugin/ContentTypePlugin.php, src/Plugin/CookiePlugin.php, src/Plugin/DecoderPlugin.php
Went over the code again to find places where we can add type hints.
=> add missing type declarations

composer.json
Better, so that composer can't load the master branch in place of 2.1.x, since master is actually 2.0.x.
=> A better branch alias would be 2.0.x

.travis.yml, composer.json
| Related tickets | fixes #148 
=> Drop PHP7.0

CHANGELOG.md, src/Exception/CircularRedirectionException.php, src/Exception/ClientErrorException.php, src/Exception/HttpClientNotFoundException.php, src/Exception/LoopException.php, src/Exception/MultipleRedirectionException.php, src/Exception/ServerErrorException.php
=> Made exceptions final

CHANGELOG.md, spec/HttpClientRouterSpec.php, src/Exception/HttpClientNoMatchException.php, src/HttpClientRouter.php
| Related tickets | fixes #44 
=> Added HttpClientNoMatchException for HttpClientRouter

spec/Plugin/ErrorPluginSpec.php, spec/Plugin/RedirectPluginSpec.php, src/Deferred.php, src/Exception/BatchException.php, src/HttpClientPool.php, src/HttpClientPool/HttpClientPool.php, src/HttpClientPool/HttpClientPoolItem.php, src/HttpClientRouter.php, src/HttpClientRouterInterface.php, src/HttpMethodsClient.php, src/HttpMethodsClientInterface.php, src/Plugin/AddHostPlugin.php, src/Plugin/CookiePlugin.php, src/Plugin/RedirectPlugin.php
some more strict types where we can. the `: void` is useful for tools that report when the return value of a void method is being used.
=> type declarations for php 7.1

CHANGELOG.md, spec/Plugin/RetryPluginSpec.php, src/Plugin/RetryPlugin.php
| Deprecations?   | yes
| Related tickets | fixes #126 
| Documentation   | https://github.com/php-http/documentation/pull/246
Add retry for responses with a server error status code.
=> retry http 5xx status as well

src/HttpClientPool.php, src/HttpClientPoolItem.php, src/HttpClientRouter.php, src/PluginClient.php
I found that some were missing.
=> [1.x] Added type hints for ClientInterface

src/Plugin/HistoryPlugin.php, src/Plugin/Journal.php, src/Plugin/RetryPlugin.php
| BC breaks?      |yes
| Related tickets | fixes #160 
=> Updated the exceptions we are using

src/HttpClientRouter.php, src/PluginClient.php
I found another minor thing =)
=> Make sure we check for PSR client

CHANGELOG.md, src/BatchClientInterface.php, src/Exception/BatchException.php, src/Plugin/ContentTypePlugin.php, src/PluginClient.php, src/PluginClientFactory.php
Minor thing.. 
What do you think about doing an RC-1 after this is merged?
=> Update date in changelog

composer.json
The old version constraint was `^3.4.20 || ^4.0.15 || ^4.1.9 || ^4.2.1"`. This would allow 4.1.0 to be installed, but I suppose this was not intended.
---
Closes #174.
=> [2.0] Added support for Symfony 5 and fixed incorrect version operators

.travis.yml, composer.json
PHP 7.4 released, and we need run tests for 7.4 too
| Related tickets | no
| Documentation   | no
PHP 7.4 released, and we need run tests for 7.4 too
=> Add 7.4 for travis

src/PluginClientBuilder.php, tests/PluginClientBuilderTest.php
| Related tickets | fixes #96 
| Documentation   | None, for now ?
This adds a plugin client builder, that allows to dynamically build a plugin client with plugins set on the go.
If you have some conditions on your plugin client (such as the auth can vary, some more headers can be dynamically added, ... like in the github's api from knp or my behat extension for http calls), it can be useful to not have a static plugin client with its plugin list, but to be able to add / remove them when needed.
As mentionned in the two repositories ([https://github.com/KnpLabs/php-github-api/blob/2.10.1/lib/Github/Client.php#L314-L331](Github's …
=> Add plugin client builder

composer.json, tests/Plugin/AddPathPluginTest.php
this pr adds missing phpunit dev dependencies, fixes existing tests and sets base php platform in composer to ensure only compatible dependencies
| Related tickets | fix #182 
- adds required dev dependencies to composer.json to run existing phpunit tests
- fixes existing phpunit tests
- adds phpunit execution to composer test scripts
- adds base platform to composer.json to ensure only php 7.1 compatible dependencies getting added
Existing PHPUnit tests should get executed during CI runs.
=> adds phpunit as dev dependency

composer.json
Allow lower version of symfony/options-resolver
Hello, I'm working at Blablacar and our PHP monolith is still running on Symfony 2.8.x.
We are working pieces by pieces on migrating to 3.x but believe me it is not an easy task.
In the meantime, not allowing options-resolver 2.x prevent us from integrating a various numbers of internal php sdk that are already using httplug 2.x abstraction.
Therefore I was was wondering if there was a specific reason for preventing the use of options-resolver 2.x and removing it in httplug 2.x (it was previously authorised in httplug 1.x)?
There is no incompatibility issue …
=> allow symfony/options-resolver:^2.6 as dependency

.php_cs.dist, spec/BatchClientSpec.php, spec/BatchResultSpec.php, spec/EmulatedHttpAsyncClientSpec.php, spec/EmulatedHttpClientSpec.php, spec/Exception/BatchExceptionSpec.php, spec/FlexibleHttpClientSpec.php, spec/HttpClientPool/HttpClientPoolItemSpec.php, spec/HttpClientPool/LeastUsedClientPoolSpec.php, spec/HttpClientPool/RandomClientPoolSpec.php, spec/HttpClientPool/RoundRobinClientPoolSpec.php, spec/HttpClientRouterSpec.php, spec/Plugin/AddHostPluginSpec.php, spec/Plugin/AddPathPluginSpec.php, spec/Plugin/AuthenticationPluginSpec.php, spec/Plugin/BaseUriPluginSpec.php, spec/Plugin/ContentLengthPluginSpec.php, spec/Plugin/CookiePluginSpec.php, spec/Plugin/DecoderPluginSpec.php, spec/Plugin/ErrorPluginSpec.php, spec/Plugin/HistoryPluginSpec.php, spec/Plugin/QueryDefaultsPluginSpec.php, spec/Plugin/RequestMatcherPluginSpec.php, spec/Plugin/RetryPluginSpec.php, spec/PluginClientFactorySpec.php, spec/PluginClientSpec.php, src/BatchResult.php, src/Exception/BatchException.php, src/HttpClientPool/HttpClientPoolItem.php
symfony settings added a new default setting to force exceptions on one line. this breaks ci because we do have longer exceptions.
=> fix cs config

composer.json, src/HttpMethodsClient.php
`Http\Discovery\MessageFactoryDiscovery`  is deprecated, so there is no way to discover a `Http\Message\RequestFactory` instance using non-deprecated APIs. `Http\Client\Common\HttpMethodsClient` should therefore except a PSR17 request factory `Psr\Http\Message\RequestFactoryInterface` as well as a `Http\Message\RequestFactory`.
=> Support the PSR17 request factory

spec/FlexibleHttpClientSpec.php, src/FlexibleHttpClient.php, src/HttpClientPool/HttpClientPool.php, src/HttpClientPool/HttpClientPoolItem.php, src/HttpClientRouter.php, src/PluginClient.php, src/PluginClientBuilder.php, src/PluginClientFactory.php
| New feature?    |yes
This PR consistently implements union type checking. Note that in the cases where there wasn't already a type check in place, the code would have still crashed later, but it is much harder for a programmer to know what went wrong, because it wasn't thrown early enough, where they actually made the made method called, and instead was thrown from deeper in the internals.
=> Consitent implementation of union type checking

src/PluginChain.php, src/PluginClient.php, tests/PluginChainTest.php
| Related tickets | fixes #184
There is a big memory leak when using the PluginClient with plugins.
Example code to reproduce the issue:
```php
use Http\Client\Curl\Client;
$samples = 50;
$curlClient = new Client();
$requestFactory = $container->get(\Psr\Http\Message\RequestFactoryInterface::class);
$pluginClient = new \Http\Client\Common\PluginClient(
$curlClient,
[
new \Http\Client\Common\Plugin\RedirectPlugin(),
]
);
$request = $requestFactory->createRequest('GET', 'https://google.it');
for ($i = 1; $i <= $samples; $i++) {
$pluginClient->sendRequest($request);
echo 'memory: ' . memory_get_usage() . PHP_EOL;
// …
```
=> Replacement memory leak hotfix

composer.json
Like the others, this is good practice, since we explicitly uses classes from this package.
=> Added explicit psr/http-client dependency

src/Plugin.php
| BC breaks?      | no|
| Deprecations?   | no|yes
Static analysers (such as Psalm) complain if someone adds this typing information to their own class which extends this interface because what they have affectively done is specialised the types, which is not allowed. It's the same as an interface saying `string|int` but the implementation only accepting `string`. So, with this in mind, we should take the opportunity to provide the most specific type information we can.
For reference, an error produced by Psalm (without this PR):
```
ERROR: MoreSpecificImplementedParamType - src/HttpClient/Plugin/Authentication.php:62:71 - Argument 2 of …
```
=> More specific plugin type doc

composer.json, src/HttpMethodsClient.php
| Deprecations?   | yes
| Related tickets | fixes #201
The PSR request factory doesn't know anything about headers or body, and these parameters are silently thrown away!
In order to avoid these, we must set them on the request afterwards. Note that by doing this we have revealed a hidden dependency on a stream factory. I have allowed for this in BC-preserving manner.
=> Fix broken HttpMethodsClient with PSR RequestFactory

phpstan.neon.dist, src/BatchResult.php
Adjust some phpstan configuration and better document BatchResult class.
Fix phpstan build.
=> fix phpstan errors

src/Plugin/AddPathPlugin.php
…ble php 5.6
| Related tickets | fixes #187 
Just apply the same fix for spl_object_hash collisions for an oldest tag compatible with php5.x
Because old projects using PHP 5.x need also this fix
=> Remove spl_object_hash to a version compatible PHP 5.X

.github/workflows/tests.yml, .gitignore, composer.json
| Related tickets | None
Update `composer.json` to allow the upcoming `^6.0` for `symfony/options-resolver`.
To support Symfony 6.
=> Dependency: Symfony/options-resolver allow ^6.0

composer.json, phpstan.neon.dist, src/HttpMethodsClient.php, src/Plugin/AddHostPlugin.php, src/Plugin/ContentTypePlugin.php, src/Plugin/CookiePlugin.php, src/Plugin/DecoderPlugin.php, src/Plugin/ErrorPlugin.php, src/Plugin/RedirectPlugin.php, src/Plugin/RetryPlugin.php, src/Plugin/SeekableBodyPlugin.php, src/PluginChain.php, src/PluginClient.php, src/PluginClientFactory.php
| Related tickets | mentioned in #215
Adjust to new phpstan version, cleanup some phpdoc
=> cleanups found with phpstan

CHANGELOG.md, spec/Plugin/RedirectPluginSpec.php, src/Plugin/RedirectPlugin.php, tests/Plugin/RedirectPluginTest.php
| Related tickets | fixes #217
| Documentation   |
=> RedirectPlugin: Default to empty path when Location doesn't specify any
